### ISSUE TITLE
请问怎么打印？

### ISSUE THREAD

**Issue by randomwangran** [linyuxuanlin/3D-print-USBDisk#1]
我 git clone 到了我的电脑？

然后呢？

**Comment by linyuxuanlin** [comment]
.stl 文件是 3D 模型，要用切片软件转化为 .gcode，然后投喂 3D 打印机打印出来 :)

**Comment by linyuxuanlin** [comment]
@randomwangran .stl 文件是 3D 模型，要用切片软件转化为 .gcode，然后投喂 3D 打印机打印出来 :)
